<?php

namespace Tests\Feature;

use App\Models\Prospect;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class UrlShortenerTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
        $this->actingAs(User::factory()->create());
    }

    public function test_url_shortener()
    {
        $this->withoutExceptionHandling();
        $prospect_make = Prospect::factory()->make();

        $call = $this->post('/prospects', $prospect_make->toArray());
        $prospect = Prospect::latest()->first();
        $call->assertStatus(302)->assertRedirect(route('prospects.index'));

        $this->assertStringContainsString('1', $prospect->google_maps_link);

        $call = $this->get($prospect->google_maps_link);
        $call->assertStatus(302);
        $call->assertRedirect($prospect_make->google_maps_link);
    }
}
